// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: text_storage/text_storage.proto

package text_storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"` // txt | pdf
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTextRequest) Reset() {
	*x = SaveTextRequest{}
	mi := &file_text_storage_text_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTextRequest) ProtoMessage() {}

func (x *SaveTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_storage_text_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTextRequest.ProtoReflect.Descriptor instead.
func (*SaveTextRequest) Descriptor() ([]byte, []int) {
	return file_text_storage_text_storage_proto_rawDescGZIP(), []int{0}
}

func (x *SaveTextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveTextRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SaveTextRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SaveTextRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SaveTextRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type SaveTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextId        string                 `protobuf:"bytes,1,opt,name=text_id,json=textId,proto3" json:"text_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTextResponse) Reset() {
	*x = SaveTextResponse{}
	mi := &file_text_storage_text_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTextResponse) ProtoMessage() {}

func (x *SaveTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_text_storage_text_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTextResponse.ProtoReflect.Descriptor instead.
func (*SaveTextResponse) Descriptor() ([]byte, []int) {
	return file_text_storage_text_storage_proto_rawDescGZIP(), []int{1}
}

func (x *SaveTextResponse) GetTextId() string {
	if x != nil {
		return x.TextId
	}
	return ""
}

type GetTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextId        string                 `protobuf:"bytes,1,opt,name=text_id,json=textId,proto3" json:"text_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTextRequest) Reset() {
	*x = GetTextRequest{}
	mi := &file_text_storage_text_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextRequest) ProtoMessage() {}

func (x *GetTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_storage_text_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextRequest.ProtoReflect.Descriptor instead.
func (*GetTextRequest) Descriptor() ([]byte, []int) {
	return file_text_storage_text_storage_proto_rawDescGZIP(), []int{2}
}

func (x *GetTextRequest) GetTextId() string {
	if x != nil {
		return x.TextId
	}
	return ""
}

type GetTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          *Text                  `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTextResponse) Reset() {
	*x = GetTextResponse{}
	mi := &file_text_storage_text_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextResponse) ProtoMessage() {}

func (x *GetTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_text_storage_text_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextResponse.ProtoReflect.Descriptor instead.
func (*GetTextResponse) Descriptor() ([]byte, []int) {
	return file_text_storage_text_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetTextResponse) GetText() *Text {
	if x != nil {
		return x.Text
	}
	return nil
}

type ListTextsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTextsRequest) Reset() {
	*x = ListTextsRequest{}
	mi := &file_text_storage_text_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTextsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTextsRequest) ProtoMessage() {}

func (x *ListTextsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_storage_text_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTextsRequest.ProtoReflect.Descriptor instead.
func (*ListTextsRequest) Descriptor() ([]byte, []int) {
	return file_text_storage_text_storage_proto_rawDescGZIP(), []int{4}
}

func (x *ListTextsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListTextsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTextsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTextsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []*Text                `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTextsResponse) Reset() {
	*x = ListTextsResponse{}
	mi := &file_text_storage_text_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTextsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTextsResponse) ProtoMessage() {}

func (x *ListTextsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_text_storage_text_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTextsResponse.ProtoReflect.Descriptor instead.
func (*ListTextsResponse) Descriptor() ([]byte, []int) {
	return file_text_storage_text_storage_proto_rawDescGZIP(), []int{5}
}

func (x *ListTextsResponse) GetTexts() []*Text {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *ListTextsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextId        string                 `protobuf:"bytes,1,opt,name=text_id,json=textId,proto3" json:"text_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTextRequest) Reset() {
	*x = DeleteTextRequest{}
	mi := &file_text_storage_text_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTextRequest) ProtoMessage() {}

func (x *DeleteTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_storage_text_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTextRequest.ProtoReflect.Descriptor instead.
func (*DeleteTextRequest) Descriptor() ([]byte, []int) {
	return file_text_storage_text_storage_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTextRequest) GetTextId() string {
	if x != nil {
		return x.TextId
	}
	return ""
}

type DeleteTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTextResponse) Reset() {
	*x = DeleteTextResponse{}
	mi := &file_text_storage_text_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTextResponse) ProtoMessage() {}

func (x *DeleteTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_text_storage_text_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTextResponse.ProtoReflect.Descriptor instead.
func (*DeleteTextResponse) Descriptor() ([]byte, []int) {
	return file_text_storage_text_storage_proto_rawDescGZIP(), []int{7}
}

type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_text_storage_text_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_text_storage_text_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_text_storage_text_storage_proto_rawDescGZIP(), []int{8}
}

func (x *Text) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Text) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Text) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Text) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Text) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Text) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Text) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SaveAnalysisResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextId        string                 `protobuf:"bytes,1,opt,name=text_id,json=textId,proto3" json:"text_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ResultJson    []byte                 `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAnalysisResultRequest) Reset() {
	*x = SaveAnalysisResultRequest{}
	mi := &file_text_storage_text_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAnalysisResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAnalysisResultRequest) ProtoMessage() {}

func (x *SaveAnalysisResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_storage_text_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAnalysisResultRequest.ProtoReflect.Descriptor instead.
func (*SaveAnalysisResultRequest) Descriptor() ([]byte, []int) {
	return file_text_storage_text_storage_proto_rawDescGZIP(), []int{9}
}

func (x *SaveAnalysisResultRequest) GetTextId() string {
	if x != nil {
		return x.TextId
	}
	return ""
}

func (x *SaveAnalysisResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SaveAnalysisResultRequest) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

type SaveAnalysisResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultId      string                 `protobuf:"bytes,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAnalysisResultResponse) Reset() {
	*x = SaveAnalysisResultResponse{}
	mi := &file_text_storage_text_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAnalysisResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAnalysisResultResponse) ProtoMessage() {}

func (x *SaveAnalysisResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_text_storage_text_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAnalysisResultResponse.ProtoReflect.Descriptor instead.
func (*SaveAnalysisResultResponse) Descriptor() ([]byte, []int) {
	return file_text_storage_text_storage_proto_rawDescGZIP(), []int{10}
}

func (x *SaveAnalysisResultResponse) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

type GetAnalysisResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisResultRequest) Reset() {
	*x = GetAnalysisResultRequest{}
	mi := &file_text_storage_text_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisResultRequest) ProtoMessage() {}

func (x *GetAnalysisResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_storage_text_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisResultRequest.ProtoReflect.Descriptor instead.
func (*GetAnalysisResultRequest) Descriptor() ([]byte, []int) {
	return file_text_storage_text_storage_proto_rawDescGZIP(), []int{11}
}

func (x *GetAnalysisResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetAnalysisResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TextId        string                 `protobuf:"bytes,2,opt,name=text_id,json=textId,proto3" json:"text_id,omitempty"`
	JobId         string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ResultJson    []byte                 `protobuf:"bytes,4,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisResultResponse) Reset() {
	*x = GetAnalysisResultResponse{}
	mi := &file_text_storage_text_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisResultResponse) ProtoMessage() {}

func (x *GetAnalysisResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_text_storage_text_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisResultResponse.ProtoReflect.Descriptor instead.
func (*GetAnalysisResultResponse) Descriptor() ([]byte, []int) {
	return file_text_storage_text_storage_proto_rawDescGZIP(), []int{12}
}

func (x *GetAnalysisResultResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAnalysisResultResponse) GetTextId() string {
	if x != nil {
		return x.TextId
	}
	return ""
}

func (x *GetAnalysisResultResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetAnalysisResultResponse) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

func (x *GetAnalysisResultResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_text_storage_text_storage_proto protoreflect.FileDescriptor

const file_text_storage_text_storage_proto_rawDesc = "" +
	"\n" +
	"\x1ftext_storage/text_storage.proto\x12\ftext_storage\"\x8e\x01\n" +
	"\x0fSaveTextRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\"+\n" +
	"\x10SaveTextResponse\x12\x17\n" +
	"\atext_id\x18\x01 \x01(\tR\x06textId\")\n" +
	"\x0eGetTextRequest\x12\x17\n" +
	"\atext_id\x18\x01 \x01(\tR\x06textId\"9\n" +
	"\x0fGetTextResponse\x12&\n" +
	"\x04text\x18\x01 \x01(\v2\x12.text_storage.TextR\x04text\"Y\n" +
	"\x10ListTextsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"S\n" +
	"\x11ListTextsResponse\x12(\n" +
	"\x05texts\x18\x01 \x03(\v2\x12.text_storage.TextR\x05texts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\",\n" +
	"\x11DeleteTextRequest\x12\x17\n" +
	"\atext_id\x18\x01 \x01(\tR\x06textId\"\x14\n" +
	"\x12DeleteTextResponse\"\xb2\x01\n" +
	"\x04Text\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"l\n" +
	"\x19SaveAnalysisResultRequest\x12\x17\n" +
	"\atext_id\x18\x01 \x01(\tR\x06textId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\fR\n" +
	"resultJson\"9\n" +
	"\x1aSaveAnalysisResultResponse\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\tR\bresultId\"1\n" +
	"\x18GetAnalysisResultRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x9b\x01\n" +
	"\x19GetAnalysisResultResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atext_id\x18\x02 \x01(\tR\x06textId\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vresult_json\x18\x04 \x01(\fR\n" +
	"resultJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt2\x95\x04\n" +
	"\x12TextStorageService\x12I\n" +
	"\bSaveText\x12\x1d.text_storage.SaveTextRequest\x1a\x1e.text_storage.SaveTextResponse\x12F\n" +
	"\aGetText\x12\x1c.text_storage.GetTextRequest\x1a\x1d.text_storage.GetTextResponse\x12L\n" +
	"\tListTexts\x12\x1e.text_storage.ListTextsRequest\x1a\x1f.text_storage.ListTextsResponse\x12O\n" +
	"\n" +
	"DeleteText\x12\x1f.text_storage.DeleteTextRequest\x1a .text_storage.DeleteTextResponse\x12g\n" +
	"\x12SaveAnalysisResult\x12'.text_storage.SaveAnalysisResultRequest\x1a(.text_storage.SaveAnalysisResultResponse\x12d\n" +
	"\x11GetAnalysisResult\x12&.text_storage.GetAnalysisResultRequest\x1a'.text_storage.GetAnalysisResultResponseB@Z>github.com/Aleveins/book-emotions-analyzer/pkg/pb/text_storageb\x06proto3"

var (
	file_text_storage_text_storage_proto_rawDescOnce sync.Once
	file_text_storage_text_storage_proto_rawDescData []byte
)

func file_text_storage_text_storage_proto_rawDescGZIP() []byte {
	file_text_storage_text_storage_proto_rawDescOnce.Do(func() {
		file_text_storage_text_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_text_storage_text_storage_proto_rawDesc), len(file_text_storage_text_storage_proto_rawDesc)))
	})
	return file_text_storage_text_storage_proto_rawDescData
}

var file_text_storage_text_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_text_storage_text_storage_proto_goTypes = []any{
	(*SaveTextRequest)(nil),            // 0: text_storage.SaveTextRequest
	(*SaveTextResponse)(nil),           // 1: text_storage.SaveTextResponse
	(*GetTextRequest)(nil),             // 2: text_storage.GetTextRequest
	(*GetTextResponse)(nil),            // 3: text_storage.GetTextResponse
	(*ListTextsRequest)(nil),           // 4: text_storage.ListTextsRequest
	(*ListTextsResponse)(nil),          // 5: text_storage.ListTextsResponse
	(*DeleteTextRequest)(nil),          // 6: text_storage.DeleteTextRequest
	(*DeleteTextResponse)(nil),         // 7: text_storage.DeleteTextResponse
	(*Text)(nil),                       // 8: text_storage.Text
	(*SaveAnalysisResultRequest)(nil),  // 9: text_storage.SaveAnalysisResultRequest
	(*SaveAnalysisResultResponse)(nil), // 10: text_storage.SaveAnalysisResultResponse
	(*GetAnalysisResultRequest)(nil),   // 11: text_storage.GetAnalysisResultRequest
	(*GetAnalysisResultResponse)(nil),  // 12: text_storage.GetAnalysisResultResponse
}
var file_text_storage_text_storage_proto_depIdxs = []int32{
	8,  // 0: text_storage.GetTextResponse.text:type_name -> text_storage.Text
	8,  // 1: text_storage.ListTextsResponse.texts:type_name -> text_storage.Text
	0,  // 2: text_storage.TextStorageService.SaveText:input_type -> text_storage.SaveTextRequest
	2,  // 3: text_storage.TextStorageService.GetText:input_type -> text_storage.GetTextRequest
	4,  // 4: text_storage.TextStorageService.ListTexts:input_type -> text_storage.ListTextsRequest
	6,  // 5: text_storage.TextStorageService.DeleteText:input_type -> text_storage.DeleteTextRequest
	9,  // 6: text_storage.TextStorageService.SaveAnalysisResult:input_type -> text_storage.SaveAnalysisResultRequest
	11, // 7: text_storage.TextStorageService.GetAnalysisResult:input_type -> text_storage.GetAnalysisResultRequest
	1,  // 8: text_storage.TextStorageService.SaveText:output_type -> text_storage.SaveTextResponse
	3,  // 9: text_storage.TextStorageService.GetText:output_type -> text_storage.GetTextResponse
	5,  // 10: text_storage.TextStorageService.ListTexts:output_type -> text_storage.ListTextsResponse
	7,  // 11: text_storage.TextStorageService.DeleteText:output_type -> text_storage.DeleteTextResponse
	10, // 12: text_storage.TextStorageService.SaveAnalysisResult:output_type -> text_storage.SaveAnalysisResultResponse
	12, // 13: text_storage.TextStorageService.GetAnalysisResult:output_type -> text_storage.GetAnalysisResultResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_text_storage_text_storage_proto_init() }
func file_text_storage_text_storage_proto_init() {
	if File_text_storage_text_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_text_storage_text_storage_proto_rawDesc), len(file_text_storage_text_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_text_storage_text_storage_proto_goTypes,
		DependencyIndexes: file_text_storage_text_storage_proto_depIdxs,
		MessageInfos:      file_text_storage_text_storage_proto_msgTypes,
	}.Build()
	File_text_storage_text_storage_proto = out.File
	file_text_storage_text_storage_proto_goTypes = nil
	file_text_storage_text_storage_proto_depIdxs = nil
}
