// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: text_storage/text_storage.proto

package text_storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TextStorageService_SaveText_FullMethodName           = "/text_storage.TextStorageService/SaveText"
	TextStorageService_GetText_FullMethodName            = "/text_storage.TextStorageService/GetText"
	TextStorageService_ListTexts_FullMethodName          = "/text_storage.TextStorageService/ListTexts"
	TextStorageService_DeleteText_FullMethodName         = "/text_storage.TextStorageService/DeleteText"
	TextStorageService_SaveAnalysisResult_FullMethodName = "/text_storage.TextStorageService/SaveAnalysisResult"
	TextStorageService_GetAnalysisResult_FullMethodName  = "/text_storage.TextStorageService/GetAnalysisResult"
)

// TextStorageServiceClient is the client API for TextStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextStorageServiceClient interface {
	SaveText(ctx context.Context, in *SaveTextRequest, opts ...grpc.CallOption) (*SaveTextResponse, error)
	GetText(ctx context.Context, in *GetTextRequest, opts ...grpc.CallOption) (*GetTextResponse, error)
	ListTexts(ctx context.Context, in *ListTextsRequest, opts ...grpc.CallOption) (*ListTextsResponse, error)
	DeleteText(ctx context.Context, in *DeleteTextRequest, opts ...grpc.CallOption) (*DeleteTextResponse, error)
	SaveAnalysisResult(ctx context.Context, in *SaveAnalysisResultRequest, opts ...grpc.CallOption) (*SaveAnalysisResultResponse, error)
	GetAnalysisResult(ctx context.Context, in *GetAnalysisResultRequest, opts ...grpc.CallOption) (*GetAnalysisResultResponse, error)
}

type textStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTextStorageServiceClient(cc grpc.ClientConnInterface) TextStorageServiceClient {
	return &textStorageServiceClient{cc}
}

func (c *textStorageServiceClient) SaveText(ctx context.Context, in *SaveTextRequest, opts ...grpc.CallOption) (*SaveTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveTextResponse)
	err := c.cc.Invoke(ctx, TextStorageService_SaveText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textStorageServiceClient) GetText(ctx context.Context, in *GetTextRequest, opts ...grpc.CallOption) (*GetTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTextResponse)
	err := c.cc.Invoke(ctx, TextStorageService_GetText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textStorageServiceClient) ListTexts(ctx context.Context, in *ListTextsRequest, opts ...grpc.CallOption) (*ListTextsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTextsResponse)
	err := c.cc.Invoke(ctx, TextStorageService_ListTexts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textStorageServiceClient) DeleteText(ctx context.Context, in *DeleteTextRequest, opts ...grpc.CallOption) (*DeleteTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTextResponse)
	err := c.cc.Invoke(ctx, TextStorageService_DeleteText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textStorageServiceClient) SaveAnalysisResult(ctx context.Context, in *SaveAnalysisResultRequest, opts ...grpc.CallOption) (*SaveAnalysisResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveAnalysisResultResponse)
	err := c.cc.Invoke(ctx, TextStorageService_SaveAnalysisResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textStorageServiceClient) GetAnalysisResult(ctx context.Context, in *GetAnalysisResultRequest, opts ...grpc.CallOption) (*GetAnalysisResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnalysisResultResponse)
	err := c.cc.Invoke(ctx, TextStorageService_GetAnalysisResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextStorageServiceServer is the server API for TextStorageService service.
// All implementations must embed UnimplementedTextStorageServiceServer
// for forward compatibility.
type TextStorageServiceServer interface {
	SaveText(context.Context, *SaveTextRequest) (*SaveTextResponse, error)
	GetText(context.Context, *GetTextRequest) (*GetTextResponse, error)
	ListTexts(context.Context, *ListTextsRequest) (*ListTextsResponse, error)
	DeleteText(context.Context, *DeleteTextRequest) (*DeleteTextResponse, error)
	SaveAnalysisResult(context.Context, *SaveAnalysisResultRequest) (*SaveAnalysisResultResponse, error)
	GetAnalysisResult(context.Context, *GetAnalysisResultRequest) (*GetAnalysisResultResponse, error)
	mustEmbedUnimplementedTextStorageServiceServer()
}

// UnimplementedTextStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTextStorageServiceServer struct{}

func (UnimplementedTextStorageServiceServer) SaveText(context.Context, *SaveTextRequest) (*SaveTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveText not implemented")
}
func (UnimplementedTextStorageServiceServer) GetText(context.Context, *GetTextRequest) (*GetTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetText not implemented")
}
func (UnimplementedTextStorageServiceServer) ListTexts(context.Context, *ListTextsRequest) (*ListTextsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTexts not implemented")
}
func (UnimplementedTextStorageServiceServer) DeleteText(context.Context, *DeleteTextRequest) (*DeleteTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteText not implemented")
}
func (UnimplementedTextStorageServiceServer) SaveAnalysisResult(context.Context, *SaveAnalysisResultRequest) (*SaveAnalysisResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveAnalysisResult not implemented")
}
func (UnimplementedTextStorageServiceServer) GetAnalysisResult(context.Context, *GetAnalysisResultRequest) (*GetAnalysisResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnalysisResult not implemented")
}
func (UnimplementedTextStorageServiceServer) mustEmbedUnimplementedTextStorageServiceServer() {}
func (UnimplementedTextStorageServiceServer) testEmbeddedByValue()                            {}

// UnsafeTextStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextStorageServiceServer will
// result in compilation errors.
type UnsafeTextStorageServiceServer interface {
	mustEmbedUnimplementedTextStorageServiceServer()
}

func RegisterTextStorageServiceServer(s grpc.ServiceRegistrar, srv TextStorageServiceServer) {
	// If the following call panics, it indicates UnimplementedTextStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TextStorageService_ServiceDesc, srv)
}

func _TextStorageService_SaveText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextStorageServiceServer).SaveText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextStorageService_SaveText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextStorageServiceServer).SaveText(ctx, req.(*SaveTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextStorageService_GetText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextStorageServiceServer).GetText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextStorageService_GetText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextStorageServiceServer).GetText(ctx, req.(*GetTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextStorageService_ListTexts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTextsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextStorageServiceServer).ListTexts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextStorageService_ListTexts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextStorageServiceServer).ListTexts(ctx, req.(*ListTextsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextStorageService_DeleteText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextStorageServiceServer).DeleteText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextStorageService_DeleteText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextStorageServiceServer).DeleteText(ctx, req.(*DeleteTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextStorageService_SaveAnalysisResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAnalysisResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextStorageServiceServer).SaveAnalysisResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextStorageService_SaveAnalysisResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextStorageServiceServer).SaveAnalysisResult(ctx, req.(*SaveAnalysisResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextStorageService_GetAnalysisResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalysisResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextStorageServiceServer).GetAnalysisResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextStorageService_GetAnalysisResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextStorageServiceServer).GetAnalysisResult(ctx, req.(*GetAnalysisResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TextStorageService_ServiceDesc is the grpc.ServiceDesc for TextStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "text_storage.TextStorageService",
	HandlerType: (*TextStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveText",
			Handler:    _TextStorageService_SaveText_Handler,
		},
		{
			MethodName: "GetText",
			Handler:    _TextStorageService_GetText_Handler,
		},
		{
			MethodName: "ListTexts",
			Handler:    _TextStorageService_ListTexts_Handler,
		},
		{
			MethodName: "DeleteText",
			Handler:    _TextStorageService_DeleteText_Handler,
		},
		{
			MethodName: "SaveAnalysisResult",
			Handler:    _TextStorageService_SaveAnalysisResult_Handler,
		},
		{
			MethodName: "GetAnalysisResult",
			Handler:    _TextStorageService_GetAnalysisResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "text_storage/text_storage.proto",
}
